### PR TITLE
Fix external dependencies for MagicNet demo

### PR DESCRIPTION
**Pull request by bittlingmayer**
Just ripped the files from the cs.stanford.edu/people/karpathy/...  Tried to minimise changes, personally I think it's best to avoid hosting any of these external libs locally.
For the data files, because of the requests for the .txt one must still run a server to load the demo page.
I did not check if other demos are similarly broken when running locally.

### CODE REVIEW

**Comment by karpathy** [comment]
Hmmmm I agree in general it's just that I'm worried of bloating the core library with all these appendages and extra data files, etc. Do you happen to know how large these files are in terms of kb?

**Comment by bittlingmayer** [comment]
The data files together are 4.2 MB.  The JS lib is negligible (29KB).

I agree bloat is a concern, not in terms of KB but in terms of readability.

We could just link to https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data etc.  According to Talebian antifragility they will probably outlive this repo.  Same for the JS, including jQuery.

Or we could make it work at least for npm.  That would mean explicitly adding a demo/package.json with these deps and demo/Readme.md with a few lines to get started:
```
  #  Assuming you have already built convnetjs
  cd demo/
  npm install
  cp -a /node_modules/. /js/
  cd ..
  npm install http-server #  If you don't already have it
  http-server
  #  Now visit http://0.0.0.0:8080/demo/
```

I'm open to other suggestions.

**Comment by bittlingmayer** [comment]
I checked now, some of the other demos also have broken deps, mostly to MNIST data.

**Comment by bittlingmayer** [comment]
Friendly ping :-)

**Comment by karpathy** [comment]
Very sorry for late reply on these, too busy with other things :( I think I'm going to remove MagicNet altogether, which will deprecate this PR and we can keep the core library lean.

**Comment by bittlingmayer** [comment]
That works too. :-)  However because the other demos have the same problem, we should probably create an Issue then, to track what is needed for any dev to build the site (whether that is changing the source to point to external versions, adding data files to the repo or creating instructions in the README about how to get them).

**Comment by karpathy** [comment]
I mostly thought of the demos as a dump of some example code that people might refer to. Ideally it would be as you describe. But many of the demos require data (e.g. CIFAR images), which I think are too large to be put in the repo. At the very least in any case all of this should be documented in the README, which I should do. 

I'm going to close this issue and in short term will update Readme. Thanks!

**Pull request closed without merging**
