### PR TITLE
Progress thus far on using SIMD + Typed Objects.

### PR DESCRIPTION
**Pull request by thomasfosterau**
As per #32, I've been trying to rewrite convnetjs using SIMD and Typed Objects, which are both proposals for ECMAScript 2016 (ES7). In the end I also ended up rewriting most of the code in ES6 and changed the build process to use [Babel](https://babeljs.io/) and Browserify.

Unfortunately, it appears as though the Typed Objects proposal is about to be changed substantially, and SIMD is going to be modified slightly so it becomes somewhat of a subset of Typed Objects (as will Typed Arrays). Given this sort of instability as far as APIs are concerned, this repo won't currently run in any browser or in node.js. It would be possible to get it to run in Firefox Nightly with some effort.

Some changes that were necessary:
- All `Vol`s are instances of a `VolType` - so all `Vol`s of a particular `VolType` have the same preset dimensions and can't be resized.
- Support for browsers without Typed Arrays had to be dropped. I don't think this affects too many people, given it's just old versions of IE.
- Most algorithms have been made as parallel as possible using SIMD.

Some things I've also considered:
- Tried using a `use_webgl` argument, which is either `false` or a reference to a WebGL context (can easily be emulated in node.js using OpenGL bindings).

Given my branch is behind quite a few commits, and isn't actually working, I thought I'd just send through this pull request so progress thus far could be looked at/torn apart by anyone who's interested.

### CODE REVIEW

**Comment by littledan** [comment]
Sorry that I haven't looked through your code in more detail, but in your Typed Objects usage, do you need these features:
- Pointers from Typed Objects to other Typed Objects, or JS objects?
- Modifying a Typed Object directly after it's been created? Or observing a modification by changing the underlying array?
I'm wondering if this problem can be solved part of the way with value types. We may want the full Typed Objects proposal eventually, in part for WebAssembly, but I was thinking of starting with value types.

**Comment by thomasfoster96** [comment]
@littledan As far as I know, probably not to the former and yes to the latter.

A bit of background: The convnetjs library works using Vols, which are objects with two properties, `w` and `dw`, which are both three-dimensional arrays, as well as three other properties `sx`, `sy` and `depth`, which hold the sizes of the arrays.

Currently the Vols are objects and the `w` and `dw` properties are one-dimensional arrays, with `set(sx, sy, depth)`, `get(sx, sy, depth)`, `set_grad(sx, sy, depth)` and `get_grad(sx, sy, depth)` methods used to set and get values in the `w` and `dw` properties (see [this file](https://github.com/karpathy/convnetjs/blob/master/src/convnet_vol.js)). This method is awfully slow, and in some places the methods to figure out the offset of a given element (`sx`, `sy`, `depth`) are manually inlined for speed.

This pull request changes this by instead having a [`VolType` constructor](https://github.com/thomasfoster96/convnetjs/blob/master/src/structures/vol.js), from which different `Vol`s of the same dimensions can be created. Using the Firefox Nightly implementation of Typed Objects, it was possible to use the underlying ArrayBuffer of the Vols (and even their individual properties) to create a Float64Array view of the `w` and `dw` arrays and then use the SIMD load/store methods to parallelize calculations (see [this code](https://github.com/thomasfoster96/convnetjs/blob/master/src/layers/convlayer.js#L60)), as well as use nicer, faster array indexing( `myVol.w[0][2][1]` instead of `myVol.get(0, 2, 1)` and have the performance benefits of things being explicitly typed.

Note that I wrote most of this code a few months ago and only cleaned it up a little the other day to open the pull request to see what @karpathy thought of the approach (as per #32 Andrej would like an easy way to create tensors in JS) - I probably wrote this using out of date drafts for SIMD.

**Comment by littledan** [comment]
It sounds to me like this would be compatible with using value types (even if typed objects might make more sense--I don't know enough about the application to determine one way or another). Assuming you had multidimensional arrays (which has already been efficiently implemented in JS with ndarrays), value types would let you read an immutable object out of the Float64Array which represents the (w, dw) pair. Looks like you're only modifying that object within the array, not when you have a particular instance of it, so that would work.

Not sure if the SIMD load/store method will work going forward. We removed Float64x2 from Phase 1 in the name of minimalism (we didn't have a compelling use case), though it will be coming back in Phase 2. I bet most of your speedup will come from doing things in terms of arrays, and using the SIMD-accelerated load and store will be only a small speedup on top of that, but I'd be interested to hear if you have data to the contrary.

Value types might be easier for the compiler to unbox than typed objects, since the compiler doesn't have to keep track of object identity. They also overlap with existing JS objects and strong mode objects a bit less. That's why I was thinking of starting with them, but if there are really compelling use cases for Typed Objects that don't fit, then I want to figure that out too.

**Comment by thomasfoster96** [comment]
Sounds like Value Types might do - as long as `sx`, `sy` and `depth` could be implemented as getters on the `VolType`'s prototype chain.

> Looks like you're only modifying that object within the array, not when you have a particular instance of it, so that would work.

Not quite sure I follow - do you mean that the array is being modified in place?

Regarding Float64x2, I was using it because changing the precision of values from 64-bit to 32-bit could be a problem. Float64x2 would be nice to have, given numbers are by default doubles.

**Comment by littledan** [comment]
I mean that the array is being modified in place, as opposed to the objects being modified directly and having that be reflected in the array.

Well, SIMD is motivated by doing operations like add on vectors. I haven't been thinking about the load/store case. Are you doing add on multiple Float64x2 elements, or your acceleration really just came from load/store? Definitely you shouldn't switch to 32-bit floats if it doesn't suit your use case.

**Comment by thomasfoster96** [comment]
> Also, for modifications that are made in the array "behind the back of the elements"--do these need to be reflected in the objects that are read out of the array, or is it OK if reading the array element has the semantics of copying the object out of the array?

The former would be greatly preferred. I don't think copying makes much sense for this use case - if someone was to use a `VolType` using, say, HTML5 canvas image data, you've got 300px * 300px * 4 colors * 2 (w and dw) - copying would end up being a bottleneck.

I was using SIMD because a lot of the calculations in this library are easily parallelizable. Ideally a lot of these calculations could be done using OpenGL bindings or WebGL, but for a good chunk of use cases of this library the CPU is good enough, and thus it makes sense to use SIMD. For example, there's a few spots where there are a dozen or more add/subtract/divide/multiply operations on a number - makes sense to do that in parallel as far as I'm concerned.

**Pull request closed without merging**
