### PR TITLE
Refactored the demos

### PR DESCRIPTION
**Pull request by pavelpep**
I extracted styles and javascript from all the demo files,
explicitly declared several magic constants in mnist and cifar demos, 
unified the javascript for mnist and cifar10 into one js file,
moved js and css files to respective folders and updated references in html 
added ability to test with own image in cifar10 and mnist demos

still left to do:
refactor and/or unify the javascript files for the rest of the demos

### CODE REVIEW

**Comment by karpathy** [comment]
Whoa, nice! This looks like an extensive commit; I assume you verified that the demos work? I skimmed through the changes but I don't think I'll have time for a thorough look.

**Comment by pavelpep** [comment]
Yes, I tested all the demos and they behave correctly. I also checked the console for errors and unimported js/css files, all clear :)

**Comment by karpathy** [comment]
looks good, great, thank you!

**Comment by pavelpep** [comment]
My pleasure! Great job on the whole project :)

**Comment by cbovar** [comment]
@pavelpep should it be `<image_channels` rather than `<3` [here](https://github.com/karpathy/convnetjs/blob/72b4719f6b7bf1ce460549a9b2c2070a7e653bc6/demo/js/images-demo.js#L24) and [here](https://github.com/karpathy/convnetjs/blob/72b4719f6b7bf1ce460549a9b2c2070a7e653bc6/demo/js/images-demo.js#L60)?

Thanks for the work! 
(Should I do a pull request if I spot such error?)

**Comment by pavelpep** [comment]
@cbovar nice catch! You are correct, it should be ```<image_channels``` instead of ```<3```

**Pull request merged**
